### ISSUE TITLE
Commanders Act multi-player analytics issue

### ISSUE THREAD

**Issue by amtins** [SRGSSR/pillarbox-web#272]
## Description

The ticker [ADI-267](https://srgssr-ch.atlassian.net/browse/ADI-267) describes media playback tracking issues when the web page contains multiple instances of the player. Since this use case can only be handled by our tag manager (Commanders Act), we need to create a new container.

## Acceptance criteria

- Each player instance on the same page must be tracked correctly.

## Tasks

- [ ] POC of the new solution
- [ ] Create a new Commanders Act container that can handle multiple player instances
- [ ] Update player to adapt to new container

**Comment by amtins** [comment]
I spoke to Mario from the ADI team to find out if they minded all the media data being sent to each player event. The answer was: "As long as it keeps working, it doesn't matter".

The advantage of sending media data to each player event is that it no longer affects the number of player instances.

However, it remains to be seen whether other Commanders Act containers used data from `media_*` variables.

Finally, we need to adapt Comscore's instantiation so that there are as many instances as there are players.

**Comment by amtins** [comment]
After discussing with RTS, RTS UDP can't be decoupled from Play's container. The reason is snowplow creates a new session id each time the session is loaded.

**Comment by amtins** [comment]
After a careful reading of the Comscore documentation, it seems that either we have an incomplete version of the documentation or the SDK has evolved. As a result, the way Comscore is initialized on the Commanders Act side may no longer be entirely up to date.

An e-mail has been sent to Comscore to clarify the situation.

**Comment by amtins** [comment]
Most external variables now have their counterparts in event variables, to make it easier to handle multiple instances.

- `Comscore` has been integrated
- `Webtrekk` has been integrated
- `Chartbeat` still needs a little work, so contact Charbeat support for more details on multi-instance

_At this stage, there is no guarantee that integration will be correct._

This task has been paused to allow time for other tasks.

**Comment by amtins** [comment]
## Conclusion

Chartbeat has been integrated, completing the transition work so that only event variables are used, thereby allowing multiple instances of the player. See ticket **ADI-267** for details.

## Miscellaneous changes :

- ability to display each tag's logs by enabling debug mode `tC.setCookie('tCdebugLib', 1, 30);`
- add a function to normalize the language code `tC.internalvars.languageFormat`

## To be validated with/by the ADI team

- find a proper name for this new container
- adding an event variable named `media_player_id` could be useful to distinguish between player instances
- adding an event variable named `media_event_id/name` could be useful to avoid confusion between other events even though event variables (_tc_array_events_) are set per event
- validate that everything still works as expected

**Comment by amtins** [comment]
A new task will be open if need. Thank you @waliid for the suggestion.
